CREATE TABLE PERSON(
ID                  SERIAL NOT NULL,
TITLE               VARCHAR(20) DEFAULT NULL,
FIRST_NAME          VARCHAR(20) DEFAULT NULL,
MIDDLE_NAME         VARCHAR(20) DEFAULT NULL,
LAST_NAME           VARCHAR(20) DEFAULT NULL,
SUFFIX              VARCHAR(20) DEFAULT NULL,
STREET              VARCHAR(255) DEFAULT NULL,
BARANGAY            VARCHAR(255) DEFAULT NULL,
CITY                VARCHAR(255) DEFAULT NULL,
ZIP                 VARCHAR(4) DEFAULT NULL,
BIRTHDATE           DATE DEFAULT NULL,
GWA                 FLOAT DEFAULT NULL,
DATE_HIRED          DATE DEFAULT NULL,
CURRENTLY_EMPLOYED  BOOLEAN DEFAULT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE CONTACT(
ID                  SERIAL NOT NULL,
TYPE                VARCHAR(20) DEFAULT NULL,
INFORMATION         VARCHAR(255) DEFAULT NULL,
PERSON_ID           INTEGER,
PRIMARY KEY (ID)
);


CREATE TABLE ROLES(
ID                  SERIAL NOT NULL,
ROLE                VARCHAR(255) DEFAULT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE  PERSON_ROLE (
  PERSON_ID     INTEGER NOT NULL,
  ROLE_ID       INTEGER NOT NULL,
  PRIMARY KEY (PERSON_ID, ROLE_ID),
  CONSTRAINT FK_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID),
  CONSTRAINT FK_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID)
);