CREATE TABLE PERSON(
ID                  SERIAL NOT NULL,
TITLE               VARCHAR(20) DEFAULT NULL,
FIRST_NAME          VARCHAR(20) DEFAULT NULL,
MIDDLE_NAME         VARCHAR(20) DEFAULT NULL,
LAST_NAME           VARCHAR(20) DEFAULT NULL,
SUFFIX              VARCHAR(20) DEFAULT NULL,
STREET              VARCHAR(255) DEFAULT NULL,
BARANGAY            VARCHAR(255) DEFAULT NULL,
CITY                VARCHAR(255) DEFAULT NULL,
ZIP                 VARCHAR(4) DEFAULT NULL,
BIRTHDATE           DATE DEFAULT NULL,
GWA                 FLOAT DEFAULT NULL,
DATE_HIRED          DATE DEFAULT NULL,
CURRENTLY_EMPLOYED  BOOLEAN DEFAULT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE CONTACT(
ID                  SERIAL NOT NULL,
TYPE                VARCHAR(20) DEFAULT NULL,
INFORMATION         VARCHAR(255) DEFAULT NULL,
PERSON_ID           INTEGER,
PRIMARY KEY (ID)
);

CREATE TABLE ROLES(
ID                  SERIAL NOT NULL,
ROLE                VARCHAR(255) DEFAULT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE  PERSON_ROLE (
  PERSON_ID     INTEGER NOT NULL,
  ROLE_ID       INTEGER NOT NULL,
  PRIMARY KEY (PERSON_ID, ROLE_ID),
  CONSTRAINT FK_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID),
  CONSTRAINT FK_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID)
);

ALTER TABLE ROLES ADD CONSTRAINT UNIQUE_ROLE UNIQUE(ROLE);

ALTER TABLE CONTACT ADD CONSTRAINT UNIQUE_INFO UNIQUE(INFORMATION);

ALTER TABLE PERSON ALTER COLUMN ZIP TYPE INTEGER;

INSERT INTO ROLES (ROLE) VALUES ('TRAINEE');
INSERT INTO ROLES (ROLE) VALUES ('TRAINER');
INSERT INTO ROLES (ROLE) VALUES ('DEVELOPER');
INSERT INTO ROLES (ROLE) VALUES ('ADMIN');
INSERT INTO ROLES (ROLE) VALUES ('QA');
INSERT INTO ROLES (ROLE) VALUES ('HR');

INSERT INTO  PERSON (FIRST_NAME, MIDDLE_NAME, LAST_NAME, TITLE, SUFFIX, STREET, BARANGAY, CITY, ZIP, BIRTHDATE, GWA, DATE_HIRED, CURRENTLY_EMPLOYED) 
	VALUES ('Joshua', 'Mallapre', 'Mengote', 'Engr', 'ECE', 'Nueva Vizcaya', 'Sto Cristo', 'Quezon City', '1105', '1996-04-16', '2.5', '2018-03-05', 'true');

INSERT INTO CONTACT (TYPE, INFORMATION)	VALUES ('EMAIL', 'mengotejosh@gmail.com');
UPDATE CONTACT SET PERSON_ID=1 WHERE ID =1;

INSERT INTO CONTACT (TYPE, INFORMATION)	VALUES ('MOBILE', '09260393518');
UPDATE CONTACT SET PERSON_ID=1 WHERE ID =2;

INSERT INTO PERSON_ROLE(PERSON_ID, ROLE_ID) VALUES (1,1);

INSERT INTO  PERSON (FIRST_NAME, MIDDLE_NAME, LAST_NAME, TITLE, SUFFIX, STREET, BARANGAY, CITY, ZIP, BIRTHDATE, GWA, DATE_HIRED, CURRENTLY_EMPLOYED) 
	VALUES ('James', 'Miller', 'Ford', '', '', 'Sienna', 'Munting Pulo', 'Lipa City', '4217', '1992-05-03', '1.75', '2015-08-04', 'false');

INSERT INTO CONTACT (TYPE, INFORMATION)	VALUES ('EMAIL', 'jmf@yahoo.com');
UPDATE CONTACT SET PERSON_ID=2 WHERE ID =3;

INSERT INTO PERSON_ROLE(PERSON_ID, ROLE_ID) VALUES (2,2);
INSERT INTO PERSON_ROLE(PERSON_ID, ROLE_ID) VALUES (2,3);




